[package]
name = "ccsniffer-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.2"
crc = "3.0.1"
hxdmp = "0.2.1"
